### ISSUE TITLE
Hi, the smartphone should have root for this?

### ISSUE THREAD

**Issue by drakulaboy** [hackerxphantom/HXP_METASPLOIT#1]
I tried to install but stuck on 
>cd metasploit-framework
>cd: no such file or directory: metasploit-framework

**Comment by hackerxphantom** [comment]
U have to wait when it's install bundle

**Comment by hackerxphantom** [comment]
No Root required

**Comment by drakulaboy** [comment]
i have only this problem, it can't create the Gemfile.lock

```
1 gem installed
cat: Gemfile.lock: No such file or directory
Hacker X Phantom                            \HXP_META.sh: line 86: cd:
```
but i successfully installed and run [this version](https://github.com/gushmazuko/metasploit_in_termux/) , and [this](https://github.com/h4ck3r0/Metasploit-termux) maybe you can correct the installation script with some tweaks from there
